name: untitled2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

workspace:
  - packages/ds_components
  - packages/ds_tokens

dependencies:
  flutter:
    sdk: flutter

  intl: any

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sqflite: ^2.3.2
  flutter_modular: ^6.3.2
  dio: ^5.4.1
  google_fonts: ^6.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  http: ^1.2.1
  firebase_crashlytics: ^3.4.9
  path: ^1.9.0

  cached_network_image: 3.3.1
  open_mail_app: ^0.4.5
  skeletons: ^0.0.3
  validatorless: ^1.2.3
  cross_file: ^0.3.4+2
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.1
  flutter_polyline_points: ^2.1.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true